version: '3.9'
services:
    guestbook-go:
        build: .
        container_name: guestbook-go
        image: guestbook-go
        environment:
            - REDIS=redis:6379
        ports:
            - "8000:8000"
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - "6379:6379"
